name: example
description: utopia_wm test environment
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  utopia_wm:
    path: ..
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: any

flutter:
  uses-material-design: true