name: utopia_wm
description: Pangolin-desktop wm interface and hierarchy provider
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.0
  uuid: any

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
