name: utopia_wm
description: Pangolin-desktop wm interface and hierarchy provider
version: 2.2.0+5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
